---
name: CI

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  rubocop:
    name: Rubocop
    uses: theforeman/actions/.github/workflows/rubocop.yml@v0
    with:
      ruby: '3.3'

  steep:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - run: bundle exec rbs collection install
      - run: bundle exec rbs-inline --output lib
      - run: bundle exec steep check

  test:
    name: Tests
    needs: rubocop
    uses: theforeman/actions/.github/workflows/test-gem.yml@v0
    with:
      command: bundle exec rake test:core
